server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/cats?currentSchema=public&createDatabaseIfNotExist=true
    username: catsUser
    password: catsPass
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html